### ISSUE TITLE
Remove hardcoded exclusion of bootstrap css files in core:inject

### ISSUE THREAD

**Issue by dematerializer** [antwerpes/gulp-angular#10]
We should get rid of the [hardcoded exclusion of bootstrap css files](https://github.com/antwerpes/gulp-angular/blob/master/tasks/core/inject.coffee#L10-12) and either leave it to the end-developer to [specify overrides](https://github.com/taptapship/wiredep#bower-overrides) in their bower.json file or generally exclude css/js files if less/coffee counterparts are also specified in main.

**Comment by dbuezas** [comment]
we should take the whole bower_components folder out of src

**Comment by monestereo** [comment]
would be resolved by #24
